/** Bridge Montagent playbooks → HyperFrames CSS vars + DESIGN.md (TS port of
 * lib/hyperframes_style_bridge.py). The playbook schema is not forked; same fields, rendered as CSS. */
const FALLBACK_CSS_VARS: Record<string, string> = {
  "--color-bg": "#0B0F1A",
  "--color-fg": "#F5F5F5",
  "--color-accent": "#F59E0B",
  "--color-primary": "#2563EB",
  "--color-secondary": "#10B981",
  "--color-surface": "#111827",
  "--color-muted": "#6B7280",
  "--font-heading": "Inter",
  "--font-body": "Inter",
  "--font-mono": "JetBrains Mono",
  "--ease-primary": "cubic-bezier(0.65, 0, 0.35, 1)",
  "--ease-entrance": "cubic-bezier(0.33, 1, 0.68, 1)",
  "--ease-exit": "cubic-bezier(0.32, 0, 0.67, 0)",
  "--duration-entrance": "0.6s",
  "--duration-transition": "0.5s",
};

function first(raw: unknown, def: string): string {
  if (Array.isArray(raw) && raw.length) return String(raw[0]);
  if (typeof raw === "string" && raw) return raw;
  return def;
}
function font(typo: Record<string, any>, key: string, def: string): string {
  const node = typo[key];
  if (node && typeof node === "object") return String(node.font ?? node.family ?? def);
  if (typeof node === "string") return node;
  return def;
}
function motionEasing(motion: Record<string, any>): [string, string] {
  const pace = String(motion.pace ?? "moderate").toLowerCase();
  if (pace === "fast") return ["0.4s", "cubic-bezier(0.33, 1, 0.68, 1)"];
  if (pace === "slow") return ["0.9s", "cubic-bezier(0.65, 0, 0.35, 1)"];
  return ["0.6s", "cubic-bezier(0.5, 0, 0.5, 1)"];
}

export function styleBridge(
  playbook: Record<string, any> | null,
  editDecisions?: Record<string, any> | null
): [Record<string, string>, string] {
  const css: Record<string, string> = { ...FALLBACK_CSS_VARS };
  let sourceNote = "built-in fallback palette";
  let playbookName = "";

  if (playbook) {
    playbookName = String(playbook.name ?? playbook.id ?? playbook.display_name ?? "");
    const vl = playbook.visual_language ?? {};
    const palette = vl.color_palette ?? {};
    const typo = playbook.typography ?? {};
    const motion = playbook.motion ?? {};
    const [duration, ease] = motionEasing(motion);
    Object.assign(css, {
      "--color-bg": first(palette.background, css["--color-bg"]!),
      "--color-fg": first(palette.text, css["--color-fg"]!),
      "--color-accent": first(palette.accent, css["--color-accent"]!),
      "--color-primary": first(palette.primary, css["--color-primary"]!),
      "--color-secondary": first(palette.secondary, css["--color-secondary"]!),
      "--color-surface": first(palette.surface, css["--color-surface"]!),
      "--color-muted": first(palette.muted_text, css["--color-muted"]!),
      "--font-heading": font(typo, "heading", css["--font-heading"]!),
      "--font-body": font(typo, "body", css["--font-body"]!),
      "--font-mono": font(typo, "code", css["--font-mono"]!),
      "--ease-primary": ease,
      "--duration-entrance": duration,
    });
    sourceNote = playbookName ? `playbook \`${playbookName}\`` : "loaded playbook";
  }

  if (editDecisions) {
    const meta = editDecisions.metadata ?? {};
    if (meta.primary_color) css["--color-primary"] = String(meta.primary_color);
    if (meta.accent_color) css["--color-accent"] = String(meta.accent_color);
    if (meta.background_color) css["--color-bg"] = String(meta.background_color);
    if (meta.text_color) css["--color-fg"] = String(meta.text_color);
  }

  return [css, renderDesignMd(css, sourceNote, playbookName)];
}

function renderDesignMd(css: Record<string, string>, sourceNote: string, playbookName: string): string {
  const title = playbookName ? `# DESIGN — ${playbookName}` : "# DESIGN";
  const lines = [
    title,
    "",
    `> Generated by Montagent HyperFrames style bridge (source: ${sourceNote}).`,
    "",
    "## Colors",
    "",
    `- Background: \`${css["--color-bg"]}\``,
    `- Foreground: \`${css["--color-fg"]}\``,
    `- Primary: \`${css["--color-primary"]}\``,
    `- Accent: \`${css["--color-accent"]}\``,
    `- Secondary: \`${css["--color-secondary"]}\``,
    `- Surface: \`${css["--color-surface"]}\``,
    `- Muted text: \`${css["--color-muted"]}\``,
    "",
    "## Typography",
    "",
    `- Heading: \`${css["--font-heading"]}\``,
    `- Body: \`${css["--font-body"]}\``,
    `- Mono: \`${css["--font-mono"]}\``,
    "",
    "## Motion",
    "",
    `- Primary ease: \`${css["--ease-primary"]}\``,
    `- Entrance duration: \`${css["--duration-entrance"]}\``,
    "",
  ];
  return lines.join("\n");
}
